language: python
python:
  - 2.6
  - 2.7
  - 3.3
  - 3.4
  - 3.5
before_install: 
  - sudo apt-get update -qq
install: pip install flask && pip install celery
before_script:
  - "wget http://download.gna.org/wkhtmltopdf/0.12/0.12.2.1/wkhtmltox-0.12.2.1_linux-precise-amd64.deb"
  - "sudo dpkg -i wkhtmltox-0.12.2.1_linux-precise-amd64.deb"
script: python setup.py test